### PR TITLE
[Podspec] Make the CocoaPods validator happy

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by ashfurrow** [comment]
That's strange – our unit tests were admittedly failing before, but now the project isn't building. There's a problem with `EXPMatchers+FBSnapshotTest`.

**Comment by ashfurrow** [comment]
(I know it's not related to this PR, which looks :+1: by the way, I'm just curious.)

Looks like there are two version of the pod on trunk:

```
      - 1.0 (2014-05-19 22:04:17 UTC)
      - 1.1.0 (2014-05-19 22:07:07 UTC)
```

Could CocoaPods be getting confused between the two, semantically identical pods? Samuel, is this a known issue or should I file a bug?

**Comment by segiddins** [comment]
It's an issue I've already fixed ;)

**Comment by ashfurrow** [comment]
Okie doke, thank! :8ball:

**Pull request merged**
