### PR TITLE
@ashfurrow => some changes to expose more in our api

### PR DESCRIPTION
**Pull request by 1aurabrown**
I am trying to migrate eigen's zoomable artwork image view to use ARTiledImageScrollView, which works well in Folio. I found myself wanting some more things available to me, so these are the changes I came up with. We can decide what does or doesn't make sense, this is just an idea. Here is the corresponding eigen PR, which is also a WIP https://github.com/artsy/eigen/pull/1971.

### CODE REVIEW

**Comment by ashfurrow** [comment]
@1aurabrown Does this still need to be merged? 

@dblock I would need write access to the repo to merge, anyway :)

**Comment by dblock** [comment]
I gave @ashfurrow and @1aurabrown access to this, looking forward to seeing this project evolve!

**Comment by ashfurrow** [comment]
@1aurabrown any update on this?

**Comment by 1aurabrown** [comment]
@ashfurrow yeah, this can be ditched. this was to deal with the artwork zoom transition, but more recent changes mean i'd write it differnetly anyway. I'd rather start from scratch.

**Pull request closed without merging**
